"""
qlstm_fixed.py — QLSTM baseline with fixed (learned) VQC weights.

Key difference from QLSTMCell:
  - QLSTMCell:      phi generated by HyperNet per graph instance (no own params)
  - QLSTMCellFixed: phi are nn.Parameter — same for ALL graphs, learned via BPTT

Purpose: ablation baseline to prove that per-instance phi from HyperNet
         contributes meaningfully vs fixed phi shared across all graphs.
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F
import pennylane as qml


class QLSTMCellFixed(nn.Module):
    """
    QLSTM cell with fixed learnable VQC weights (no HyperNet).

    Same 6-VQC architecture as QLSTMCell, but phi_1...phi_6 and W_in/b_in
    are nn.Parameter — learned during training and shared across all graphs.

    Args (same interface as ClassicalLSTMCell for easy swapping):
        theta_t : (n_qaoa_params,)
        y_t     : scalar
        h_prev  : (n_qubits,)
        C_prev  : (n_qubits,)

    Returns:
        theta_next : (n_qaoa_params,)
        h_t        : (n_qubits,)
        C_t        : (n_qubits,)
    """

    def __init__(
        self,
        n_qubits:      int = 4,
        n_qlayers:     int = 2,
        n_qaoa_params: int = 4,
        concat_size:   int = 9,   # n_qaoa_params + 1 + n_qubits
        backend:       str = "default.qubit",
        diff_method:   str = "backprop",
    ) -> None:
        super().__init__()
        self.n_qubits      = n_qubits
        self.n_qlayers     = n_qlayers
        self.n_qaoa_params = n_qaoa_params
        self._diff_method  = diff_method

        # Fixed learnable weights — same for all graphs
        self.W_in  = nn.Parameter(torch.randn(n_qubits, concat_size) * 0.1)
        self.b_in  = nn.Parameter(torch.zeros(n_qubits))
        self.phi_1 = nn.Parameter(torch.randn(n_qlayers, n_qubits) * 0.1)
        self.phi_2 = nn.Parameter(torch.randn(n_qlayers, n_qubits) * 0.1)
        self.phi_3 = nn.Parameter(torch.randn(n_qlayers, n_qubits) * 0.1)
        self.phi_4 = nn.Parameter(torch.randn(n_qlayers, n_qubits) * 0.1)
        self.phi_5 = nn.Parameter(torch.randn(n_qlayers, n_qubits) * 0.1)
        self.phi_6 = nn.Parameter(torch.randn(n_qlayers, n_qubits) * 0.1)

        gate_names = ["forget", "input", "update", "output", "hidden", "theta"]
        self._wires = {
            name: [f"wire_{name}_{i}" for i in range(n_qubits)]
            for name in gate_names
        }
        self._devs = {
            name: qml.device(backend, wires=self._wires[name])
            for name in gate_names
        }

        def _make_circuit(dev, wires, diff_method):
            @qml.qnode(dev, interface="torch", diff_method=diff_method)
            def circuit(inputs, weights):
                qml.AngleEmbedding(inputs, wires=wires)
                qml.BasicEntanglerLayers(weights, wires=wires)
                return [qml.expval(qml.PauliZ(w)) for w in wires]
            return circuit

        self._circuits = {
            name: _make_circuit(self._devs[name], self._wires[name], diff_method)
            for name in gate_names
        }

    def _vqc(self, name: str, y_enc: torch.Tensor, phi: torch.Tensor) -> torch.Tensor:
        out = self._circuits[name](y_enc, phi)
        result = torch.stack(out) if isinstance(out, (list, tuple)) else out
        return result.to(y_enc.dtype)

    def forward(
        self,
        theta_t: torch.Tensor,  # (n_qaoa_params,)
        y_t:     torch.Tensor,  # scalar
        h_prev:  torch.Tensor,  # (n_qubits,)
        C_prev:  torch.Tensor,  # (n_qubits,)
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:

        dtype = torch.float64 if self._diff_method == "adjoint" else self.W_in.dtype
        theta_t = theta_t.to(dtype)
        y_t     = y_t.to(dtype)
        h_prev  = h_prev.to(dtype)
        C_prev  = C_prev.to(dtype)
        W_in    = self.W_in.to(dtype)
        b_in    = self.b_in.to(dtype)
        phi_1   = self.phi_1.to(dtype)
        phi_2   = self.phi_2.to(dtype)
        phi_3   = self.phi_3.to(dtype)
        phi_4   = self.phi_4.to(dtype)
        phi_5   = self.phi_5.to(dtype)
        phi_6   = self.phi_6.to(dtype)

        v     = torch.cat([theta_t, y_t.reshape(1), h_prev])
        y_enc = F.linear(v, W_in, b_in)

        f_t = torch.sigmoid(self._vqc("forget", y_enc, phi_1))
        i_t = torch.sigmoid(self._vqc("input",  y_enc, phi_2))
        g_t = torch.tanh   (self._vqc("update", y_enc, phi_3))
        o_t = torch.sigmoid(self._vqc("output", y_enc, phi_4))

        C_t = f_t * C_prev + i_t * g_t
        h_raw = self._vqc("hidden", y_enc, phi_5)
        h_t   = o_t * torch.tanh(h_raw)

        theta_raw  = self._vqc("theta", y_enc, phi_6)
        theta_next = theta_raw[:self.n_qaoa_params]

        return theta_next, h_t, C_t
